apiVersion: v1
kind: Pod
metadata:
  labels:
    docker: rdepot-cli
spec:
  containers:
  - name: dind
    image: 196229073436.dkr.ecr.eu-west-1.amazonaws.com/oa-infrastructure/dind
    securityContext:
      privileged: true
  - name: curl
    image: alpine/curl:latest
    securityContext:
      privileged: true
    tty: true
    command:
    - cat

