version: '3.0'
services:
  #proxy:
    #image: library/nginx:alpine
    #container_name: oa-rdepot-proxy
    #restart: unless-stopped
    #volumes:
      #- ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./docker/proxy/sites-enabled/rdepot:/etc/nginx/sites-enabled/rdepot:ro
      #- repository:/opt/rdepot/repo/:ro
    #ports:
      #- 80:80
    #depends_on:
      #- app
      #- repo
    #networks:
      #- oa-rdepot
  db:
    image: library/postgres:alpine
    restart: unless-stopped
    hostname: oa-rdepot-db
    container_name: oa-rdepot-db
    volumes:
      - ./docker/db/rdepot.sql:/docker-entrypoint-initdb.d/rdepot.sql:ro
    networks:
      - oa-rdepot
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  app:
    image: openanalytics/rdepot-app:1.4.1
    restart: unless-stopped
    hostname: oa-rdepot-app
    container_name: oa-rdepot-app
    entrypoint:  java -jar /opt/rdepot/rdepot.war
    ports:
      - 8080:8080
    networks:
      - oa-rdepot
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://oa-rdepot-db:5432/postgres
      - DB_USERNAME=postgres
      - REPOSITORIES_0_NAME=public
      - REPOSITORIES_0_PUBLICATIONURI=http://localhost/repo/public
      - REPOSITORIES_0_SERVERADDRESS=http://oa-rdepot-repo:8080/public
    healthcheck:
      test: ["CMD-SHELL", "if [ \"$$(curl -I localhost:8080 2>/dev/null | grep HTTP/1.1 | cut -d\" \" -f2)\" != \"302\" ]; then exit 1; else exit 0; fi;"]
      interval: 10s
      timeout: 10s
      retries: 10
#   repo:
#    image: openanalytics/rdepot-repo:1.4.1
#    restart: unless-stopped
#    hostname: oa-rdepot-repo
#    container_name: oa-rdepot-repo
#    volumes:
#      - repository:/opt/rdepot/
#    networks:
#      - oa-rdepot
networks:
  oa-rdepot:
    ipam:
      config:
        - subnet: 192.168.49.0/24
volumes:
  repository:
